# Generated by Django 3.1.7 on 2021-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0007_position_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='task',
            field=models.ManyToManyField(to='ttt.Task'),
        ),
    ]
