# Generated by Django 3.1.7 on 2021-05-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0020_auto_20210530_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ttt.member'),
        ),
    ]
