# Generated by Django 3.1.7 on 2021-05-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0021_task_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ttt.task', unique=True),
        ),
    ]
