# Generated by Django 3.1.7 on 2021-05-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0022_auto_20210530_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='ttt.task'),
        ),
    ]
