# Generated by Django 3.1.7 on 2021-05-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0023_auto_20210530_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='task_status',
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
