# Generated by Django 3.1.7 on 2021-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_created',
        ),
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
