# Generated by Django 3.1.7 on 2021-05-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0005_auto_20210528_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='dob',
        ),
    ]
