# Generated by Django 3.1.7 on 2021-05-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0006_remove_member_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='task_status',
            field=models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('completed', 'Completed')], max_length=200, null=True),
        ),
    ]
