# Generated by Django 3.1.7 on 2021-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0009_auto_20210528_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_owner',
        ),
        migrations.AddField(
            model_name='member',
            name='task_assigned',
            field=models.ManyToManyField(to='ttt.Task'),
        ),
        migrations.AddField(
            model_name='position',
            name='task_owner',
            field=models.ManyToManyField(related_name='Task_Owner', to='ttt.Member'),
        ),
    ]
