# Generated by Django 3.1.7 on 2021-05-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0011_remove_position_task_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='TaskStatus',
        ),
    ]
