# Generated by Django 3.1.7 on 2021-05-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0014_member_task_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='task_assigned',
        ),
    ]
