# Generated by Django 3.1.7 on 2021-05-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0017_auto_20210529_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='task_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Tester', 'Tester'), ('Support', 'Support')], max_length=100, null=True),
        ),
    ]
