# Generated by Django 3.1.7 on 2021-05-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0018_auto_20210530_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
