# Generated by Django 3.1.7 on 2021-05-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0027_auto_20210531_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ttt.task'),
        ),
    ]
